=begin

Name: Victoria Green
Course: CSC 415
Semester: Spring 2018
Instructor: Dr. Pulimood
Project name: hyperfocus
Description: studyguide generator
Filename: study_guides_helper.rb


=end

#####---------  THIS FILE WAS GENERATED BY FRAMEWORK ----------#####
#
module StudyGuidesHelper
end
