=begin
Name: Victoria Green
Course: CSC 415
Semester: Spring 2018
Instructor: Dr. Pulimood
Project name: hyperfocus
Description: studyguide generator
Filename: application_controller.rb
=end

#####---------  THIS FILE WAS GENERATED BY FRAMEWORK ----------#####
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end
