=begin

Name: Victoria Green
Course: CSC 415
Semester: Spring 2018
Instructor: Dr. Pulimood
Project name: hyperfocus
Description: studyguide generator
Filename: pages_controller.rb
Description:

=end

#####---------  THIS FILE WAS GENERATED BY FRAMEWORK ----------#####
class PagesController < ApplicationController
  def home
  end

  def new
  end

  def generate
  end

  def setTitle
  end

  def setFileName
  end

  def addFileName
  end

  def addStyleSheet
  end

  def getTitle
  end

  def getFileName
  end

  def getStyleSheet
  end

  def getContent
  end

  def download
  end
end

