=begin

Name: Victoria Green
Course: CSC 415
Semester: Spring 2018
Instructor: Dr. Pulimood
Project name: hyperfocus
Description: studyguide generator
Filename: study_guides_controller.rb0
Description: Study guide controller initializing creating and exporting

*** This file was generated by Framework ***
=end

class StudyGuidesController < ApplicationController
  before_action :set_study_guide, only: [:show, :edit, :update, :destroy]

  # GET /study_guides
  # GET /study_guides.json
  #automatically generated
  def index
    @study_guides = StudyGuide.all
  end

  # GET /study_guides/1
  # GET /study_guides/1.json
  #automatically generated
  def show
  end

  # GET /study_guides/new
  #automatically generated
  def new
    puts "making it!"
    @study_guide = StudyGuide.new
    @study_guide.sgfields.build
  end

  # GET /study_guides/1/edit
  #automatically generated
  def edit
  end

  # POST /study_guides
  # POST /study_guides.json
  #automatically generated

  # user has filled in form and has selected create study Guide
  # function takes input and saves it in params
  # an html file is created and intialized the essentials
  # potentially the user inputs would be entered into it with the appropriate tags (to be implemented)
  # after html file is created it would be converted into a pdf (to be implemented) and would re route to download pages_edit_path
  # indicating sucess and that the user can download now

  def create
    @study_guide = StudyGuide.new(study_guide_params)
    #wicked_pdf stuff

    if @study_guide.save
      #redirect_to edit_study_guide_path(@study_guide), notice: 'Study Guide Form was Successfully created.'


      html_file = File.new('public/temp.html', "w+")
      #send_data("<!DOCTYPE html>" => 'temp.html')
      html_file.puts "<!DOCTYPE html>"
      #send_data("<html lang=\"en\"> " => 'temp.html')
      html_file.puts "<html lang=\"en\"> "
      #send_data("<head>"=> 'temp.html')
      html_file.puts "<head>"
      #send_data("<meta charset=\"UTF-8\">"=> 'temp.html')
      html_file.puts "<meta charset=\"UTF-8\">"
      html_file.puts "<link href=\"https://fonts.googleapis.com/css?family=Antic+Slab|Fredoka+One|Julius+Sans+One|Permanent+Marker|Quicksand|Tajawal|Zilla+Slab\" rel=\"stylesheet\">"
       html_file.puts "<style>" + "body{
  background-color: #fff;
    font-family: 'Zilla Slab', serif;
    padding: 50px;
}
h1{
    font-family: 'Permanent Marker', cursive;
    text-align: center;
    
}

h2{
    

    /* font-family: 'Permanent Marker', cursive;
    font-family: 'Julius Sans One', sans-serif;*/
    font-family: 'Tajawal', sans-serif;
    /*font-family: 'Fredoka One', cursive;
    font-family: 'Antic Slab', serif;
    font-family: 'Zilla Slab', serif;
    font-family: 'Quicksand', sans-serif;*/
    text-align: left;
}

span{
    background-color: #fff2ac;
    background-image: linear-gradient(to right, #ffe359 0%, #fff2ac 100%);
}

 " + "</style>"
      #html_file.puts "<%= stylesheet_link_tag \"https://drive.google.com/file/d/1c5ryeqnNVD1Vzux8Ljee8CKozbm84K6Z/view?usp=sharing\" %>"
     #style sheet
      # fonts
      #send_data( "</head>" => 'temp.html')
      html_file.puts "</head>"

      html_file.puts "<body>"
      #send_data("<body>"=> 'temp.html')
=begin
      html_file.puts "<h1>"
      html_file.puts  'title'
      html_file.puts "</h1>"

      html_file.puts "<h2>"
      html_file.puts  'Mainpoint'
      html_file.puts "</h2>"

      html_file.puts "<ul>"
      html_file.puts  "<li> bullet point </li> "
      html_file.puts  "<li> bullet point </li>"
      html_file.puts "</ul>"

      html_file.puts "<ol>"
      html_file.puts  "<li> numbering </li> "
      html_file.puts  "<li> number </li>"
      html_file.puts "</ol>"
=end	
     #toprint_hash = Hash.new

      toprint_hash = study_guide_params.to_h
    
      tag = p
      span = 0;
      
      toprint_hash.each do |curr, currVal|
        if curr.to_s == 'title'
          html_file.puts "<h1>" + currVal.to_s + "</h1>"
        elsif curr.to_s == 'sgfields_attributes'
	  
	  currVal.each do |num, info|
	  	info.each do | name, value|
		 if name.to_s == 'type'
		     
		      	if value.to_s == "Heading" 
				tag = 'h2'
			elsif value.to_s == "Mainpoint" 
				tag = 'h3'
			elsif value.to_s == "Term" 
				tag = 'p'
				span = 1
			elsif value.to_s == "BulletPoint"
				tag= 'ul'
			elsif value.to_s == "Definition" 
				tag = 'p'
				span = 2
		 	elsif value.to_s == "SubBulletPoint"
				tag = "ul ul"
			else 
			   tag = "p"
		     end
		 elsif name.to_s == 'content'
			if tag == 'ol' or tag == 'ul'
			  html_file.puts "<" + tag + ">"
			  html_file.puts "<li>"+ value.to_s + "</li>"
			  html_file.puts  "</" + tag + ">"

			elsif tag == "ul ul"
			  html_file.puts "<ul> <ul>"
                          html_file.puts "<li>"+ value.to_s + "</li>"
                          html_file.puts  "</ul></ul>"
			elsif span == 1
			  html_file.puts "<"+ tag.to_s+"><span > "+ value.to_s + "</span>"
			elsif span == 2
			  html_file.puts "-" + value.to_s + "</"+tag.to_s+">"
			  span = 0;
			else
			  html_file.puts "<"+ tag.to_s+">"+ value.to_s + "</"+tag.to_s+">"
			end
                 
		 end  
		
		
		 end
		
	  end
          

        end


        end
      


      #title = toprint_hash.select { |key, value| key.to_s.match(/^title\d+/)}
      #html_file.puts  title.to_s
      #toprint_hash.delete(title)

      #toprint_hash each do |field, value|
        #value.each do |type , content|
          #case type
         # if type == 'Heading'
         #   html_file.puts "<h1> content is" + content + "</h1>"
         # else if type == 'Mainpoint'
         # else if type == 'bullet point'
         # else if type == 'numbering'
         # else if type == 'term definition'
         # else
            #html_file.puts "<h1> content is" + content + " and type is" + type + "</h1>"
         # end

      #  end


    #  end

      #send_data(study_guide_params => 'temp.html')

      html_file.puts "</body>"
      #send_data("</body>"=> 'temp.html')

      html_file.puts "</html>"
      #end_data("</html>"=> 'temp.html')
      html_file.close
	
      pdf = WickedPdf.new.pdf_from_html_file('/home/student1/Assignments/hyperfocus/code/public/temp.html')
	
      #pdf = WickedPdf.new.pdf_from_url('https://github.com/mileszs/wicked_pdf')	

send_data(pdf, :filename => "studyguide.pdf", :disposition => 'attachment', :notice => 'Study Guide was Successfully created.')

    else
      redirect_to pages_new_path
      #render :new
    end
	end


  # PATCH/PUT /study_guides/1
  # PATCH/PUT /study_guides/1.json
  # automatically generated function that would update values of studyguide
  def update
    if @study_guide.update(study_guide_params)
      redirect_to edit_study_guide_path(@study_guide), notice:'Study Guide Successfully Updated'
    else
      render :edit
    end
  end

  # DELETE /study_guides/1
  # DELETE /study_guides/1.json
  #automatically generated
  #Delete study guide
  def destroy
    @study_guide.destroy
    redirect_to study_guides_url, notice: 'Study Guide was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_study_guide
    @study_guide = StudyGuide.find(params[:id])
  end

  #automatically generated.
  def study_guide_params
    params.require(:study_guide).permit(:title, sgfields_attributes: Sgfield.attribute_names.map(&:to_sym).push(:_destroy))
  end

end
